package palette

import (
	"fmt"
	"io"
)

// v4 ghostty emitter — reads theme.json, writes ghostty.conf.
//
// Output shape (via EmitStandard):
//
//	# generated by themes v4 from <theme>/theme.json — DO NOT EDIT
//	# --- baseline ---
//	  <baselines/ghostty.tmpl>
//	# --- semantic ---
//	  background = <hex>
//	  foreground = <hex>
//	  cursor-color = <hex>
//	  background-opacity = <effects.opacity>
//	  background-blur = <effects.blur>
//	  palette = 0=<ansi[0]>  ... palette = 15=<ansi[15]>
//	# --- hints ---
//	  # (ghostty has no known hint keys today)
//	# --- overrides ---
//	  <overrides.ghostty verbatim>
//	  <overrides.ghostty_path sidecar>

type ghosttyEmitter struct{}

func (ghosttyEmitter) App() string      { return "ghostty" }
func (ghosttyEmitter) Filename() string { return "ghostty.conf" }

func (e ghosttyEmitter) Emit(t *Theme, w io.Writer) error {
	return EmitStandard(t, w, e.App(), "#", emitGhosttySemantic, NoHints)
}

func emitGhosttySemantic(t *Theme, w io.Writer) error {
	s := t.Palette.Semantic
	fmt.Fprintf(w, "background = %s\n", s.Bg)
	fmt.Fprintf(w, "foreground = %s\n", s.Fg)
	fmt.Fprintf(w, "cursor-color = %s\n", s.Cursor)
	fmt.Fprintf(w, "cursor-text = %s\n", s.Bg)
	fmt.Fprintf(w, "selection-background = %s\n", s.SelectionBg)
	fmt.Fprintf(w, "selection-foreground = %s\n", s.SelectionFg)

	// Translucency from effects.
	if t.Effects.Opacity > 0 && t.Effects.Opacity < 1 {
		fmt.Fprintf(w, "background-opacity = %s\n", trimFloat(t.Effects.Opacity))
	}
	if t.Effects.Blur > 0 {
		fmt.Fprintf(w, "background-blur = %d\n", int(t.Effects.Blur))
	}

	// 16 ANSI palette entries.
	for i, c := range t.Palette.Ansi {
		fmt.Fprintf(w, "palette = %d=%s\n", i, c)
	}
	return nil
}
