package palette

import (
	"fmt"
	"io"
	"os"
)

// v4 obsidian emitter — writes a CSS snippet that overrides Obsidian CSS variables.
type obsidianEmitter struct{}

func (obsidianEmitter) App() string      { return "obsidian" }
func (obsidianEmitter) Filename() string { return "obsidian.css" }

func (e obsidianEmitter) Emit(t *Theme, w io.Writer) error {
	if t == nil {
		return fmt.Errorf("emit obsidian: nil theme")
	}
	fmt.Fprintf(w, "/* generated by themes v4 from %s/theme.json — DO NOT EDIT */\n", t.Name)

	base, err := Baseline(e.App(), t)
	if err != nil {
		return fmt.Errorf("emit obsidian baseline: %w", err)
	}
	if base != "" {
		fmt.Fprintln(w, "\n/* --- baseline --- */")
		if _, err := io.WriteString(w, base); err != nil {
			return err
		}
		if !endsWithNewline(base) {
			fmt.Fprintln(w)
		}
	}

	fmt.Fprintln(w, "\n/* --- semantic --- */")
	if err := emitObsidianSemantic(t, w); err != nil {
		return fmt.Errorf("emit obsidian semantic: %w", err)
	}

	inline := t.OverrideInline(e.App())
	sidecar := t.OverridePath(e.App())
	if inline != "" || sidecar != "" {
		fmt.Fprintln(w, "\n/* --- overrides --- */")
		if inline != "" {
			if _, err := io.WriteString(w, inline); err != nil {
				return err
			}
			if !endsWithNewline(inline) {
				fmt.Fprintln(w)
			}
		}
		if sidecar != "" {
			data, err := os.ReadFile(sidecar)
			if err != nil {
				return fmt.Errorf("read obsidian override sidecar: %w", err)
			}
			if _, err := w.Write(data); err != nil {
				return err
			}
		}
	}
	return nil
}

func emitObsidianSemantic(t *Theme, w io.Writer) error {
	s := t.Palette.Semantic
	line := func(name, value string) {
		fmt.Fprintf(w, "\t%s: %s;\n", name, value)
	}

	fmt.Fprintln(w, "body {")
	line("--background-primary", s.Bg)
	line("--background-primary-alt", s.BgAlt)
	line("--background-secondary", s.BgAlt)
	line("--background-secondary-alt", s.SelectionBg)
	line("--background-modifier-border", s.Border)
	line("--background-modifier-border-hover", s.Muted)
	line("--background-modifier-hover", s.SelectionBg)
	line("--background-modifier-active-hover", s.SelectionBg)
	line("--background-modifier-cover", blendHex(s.Bg, s.BgAlt, 70))
	fmt.Fprintln(w)

	line("--text-normal", s.Fg)
	line("--text-muted", s.Muted)
	line("--text-faint", s.FgDim)
	line("--text-accent", s.Accent)
	line("--text-accent-hover", s.Warning)
	line("--text-selection", blendHex(s.Bg, s.Accent, 35))
	line("--text-highlight-bg", blendHex(s.Bg, s.Warning, 35))
	line("--interactive-normal", s.SelectionBg)
	line("--interactive-hover", s.Border)
	line("--interactive-accent", s.Accent)
	line("--interactive-accent-hover", s.Warning)
	fmt.Fprintln(w)

	line("--titlebar-background", s.BgAlt)
	line("--titlebar-background-focused", s.BgAlt)
	line("--tab-container-background", s.BgAlt)
	line("--tab-text-color", s.Muted)
	line("--tab-text-color-focused-active-current", s.Accent)
	line("--nav-item-color", s.Muted)
	line("--nav-item-color-active", s.Fg)
	line("--nav-item-background-active", s.SelectionBg)
	line("--nav-item-background-hover", s.SelectionBg)
	fmt.Fprintln(w)

	line("--link-color", s.Info)
	line("--link-color-hover", s.Accent)
	line("--link-external-color", s.Info)
	line("--link-external-color-hover", s.Accent)
	line("--tag-color", s.Accent)
	line("--tag-background", blendHex(s.Bg, s.Accent, 18))
	line("--tag-background-hover", blendHex(s.Bg, s.Accent, 28))
	line("--blockquote-border-color", s.Accent)
	line("--blockquote-color", s.Muted)
	line("--hr-color", s.Border)
	fmt.Fprintln(w)

	line("--code-background", s.BgAlt)
	line("--code-normal", s.Fg)
	line("--code-comment", s.Syntax.Comment)
	line("--code-function", s.Syntax.Function)
	line("--code-important", s.Syntax.Keyword)
	line("--code-keyword", s.Syntax.Keyword)
	line("--code-operator", s.Syntax.Operator)
	line("--code-property", s.Syntax.Type)
	line("--code-punctuation", s.Muted)
	line("--code-string", s.Syntax.String)
	line("--code-tag", s.Syntax.Type)
	line("--code-value", s.Syntax.Number)
	fmt.Fprintln(w)

	line("--h1-color", s.Accent)
	line("--h2-color", s.Info)
	line("--h3-color", s.Ok)
	line("--h4-color", s.Warning)
	line("--h5-color", s.Syntax.Number)
	line("--h6-color", s.Muted)
	fmt.Fprintln(w)

	line("--color-red", s.Error)
	line("--color-orange", s.Warning)
	line("--color-yellow", s.Warning)
	line("--color-green", s.Ok)
	line("--color-cyan", t.Palette.Ansi[6])
	line("--color-blue", s.Info)
	line("--color-purple", s.Syntax.Number)
	line("--color-pink", t.Palette.Ansi[13])
	line("--checkbox-color", s.Accent)
	line("--checkbox-color-hover", s.Warning)
	fmt.Fprintln(w, "}")
	return nil
}
