package palette

import (
	"bytes"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestEmitStandardOrdersFourBlocks verifies the AC-2 pipeline: writes
// baseline → semantic → hints → overrides in that order.
func TestEmitStandardOrdersFourBlocks(t *testing.T) {
	th := &Theme{Name: "test", Dir: "/tmp/test",
		Overrides: map[string]string{"tmux": "OVERRIDE_INLINE\n"}}
	var buf bytes.Buffer
	semantic := func(_ *Theme, w io.Writer) error {
		fmt.Fprintln(w, "SEMANTIC_LINE")
		return nil
	}
	hints := func(_ *Theme, w io.Writer) error {
		fmt.Fprintln(w, "HINTS_LINE")
		return nil
	}
	if err := EmitStandard(th, &buf, "tmux", "#", semantic, hints); err != nil {
		t.Fatalf("EmitStandard: %v", err)
	}
	out := buf.String()

	// Check order: baseline block comes before semantic, which comes
	// before hints, which comes before overrides.
	iBaseline := strings.Index(out, "--- baseline ---")
	iSemantic := strings.Index(out, "--- semantic ---")
	iHints := strings.Index(out, "--- hints ---")
	iOverrides := strings.Index(out, "--- overrides ---")
	if iBaseline < 0 || iSemantic < 0 || iHints < 0 || iOverrides < 0 {
		t.Fatalf("missing one or more block markers in:\n%s", out)
	}
	if !(iBaseline < iSemantic && iSemantic < iHints && iHints < iOverrides) {
		t.Fatalf("blocks out of order (baseline=%d semantic=%d hints=%d overrides=%d):\n%s",
			iBaseline, iSemantic, iHints, iOverrides, out)
	}

	// Content order matches block order.
	iSemanticLine := strings.Index(out, "SEMANTIC_LINE")
	iHintsLine := strings.Index(out, "HINTS_LINE")
	iOverrideLine := strings.Index(out, "OVERRIDE_INLINE")
	if !(iSemanticLine > 0 && iHintsLine > iSemanticLine && iOverrideLine > iHintsLine) {
		t.Errorf("content out of order:\n%s", out)
	}

	// Header present.
	if !strings.Contains(out, "generated by themes v4") {
		t.Errorf("missing header comment:\n%s", out)
	}
	if !strings.Contains(out, "from test/theme.json") {
		t.Errorf("header should mention theme name:\n%s", out)
	}
}

// TestEmitStandardSkipsOverrideBlockWhenAbsent documents the contract:
// no overrides ⇒ no --- overrides --- marker in output.
func TestEmitStandardSkipsOverrideBlockWhenAbsent(t *testing.T) {
	th := &Theme{Name: "test", Dir: "/tmp/test"}
	var buf bytes.Buffer
	semantic := func(_ *Theme, w io.Writer) error { return nil }
	if err := EmitStandard(th, &buf, "tmux", "#", semantic, NoHints); err != nil {
		t.Fatalf("EmitStandard: %v", err)
	}
	out := buf.String()
	if strings.Contains(out, "--- overrides ---") {
		t.Errorf("overrides marker should be absent when nothing to override:\n%s", out)
	}
}

// TestEmitStandardReadsSidecarPath verifies that overrides.<app>_path
// resolves relative to the theme dir and appends the file contents.
func TestEmitStandardReadsSidecarPath(t *testing.T) {
	dir := t.TempDir()
	sidecar := filepath.Join(dir, "extra.conf")
	if err := os.WriteFile(sidecar, []byte("SIDECAR_CONTENT\n"), 0o644); err != nil {
		t.Fatalf("write sidecar: %v", err)
	}
	th := &Theme{Name: "test", Dir: dir,
		Overrides: map[string]string{"tmux_path": "extra.conf"}}
	var buf bytes.Buffer
	semantic := func(_ *Theme, w io.Writer) error { return nil }
	if err := EmitStandard(th, &buf, "tmux", "#", semantic, NoHints); err != nil {
		t.Fatalf("EmitStandard: %v", err)
	}
	if !strings.Contains(buf.String(), "SIDECAR_CONTENT") {
		t.Errorf("sidecar contents not appended:\n%s", buf.String())
	}
}

// TestEmitStandardEmptyCommentPrefixOmitsMarkers documents the contract
// for JSON/XML-formatted outputs: empty prefix ⇒ no block markers.
// This lets emitters that don't tolerate # comments still use the same
// pipeline function.
func TestEmitStandardEmptyCommentPrefixOmitsMarkers(t *testing.T) {
	th := &Theme{Name: "test", Dir: "/tmp"}
	var buf bytes.Buffer
	semantic := func(_ *Theme, w io.Writer) error {
		fmt.Fprintln(w, `{"key":"value"}`)
		return nil
	}
	if err := EmitStandard(th, &buf, "no-baseline", "", semantic, NoHints); err != nil {
		t.Fatalf("EmitStandard: %v", err)
	}
	out := buf.String()
	if strings.Contains(out, "---") || strings.Contains(out, "generated by") {
		t.Errorf("empty prefix should omit markers/header:\n%s", out)
	}
}

// TestEmitStandardWrapsErrors documents the failure surface.
func TestEmitStandardWrapsErrors(t *testing.T) {
	th := &Theme{Name: "t", Dir: "/tmp/x"}
	fail := func(_ *Theme, _ io.Writer) error { return fmt.Errorf("boom") }
	err := EmitStandard(th, &bytes.Buffer{}, "tmux", "#", fail, NoHints)
	if err == nil || !strings.Contains(err.Error(), "boom") || !strings.Contains(err.Error(), "tmux") {
		t.Errorf("expected error to wrap semantic err with app name: %v", err)
	}
}
