package palette

import (
	"fmt"
	"io"
	"os"
)

// Emitter is one entry in the v4 derive pipeline. Each emitter produces
// exactly one derived file for one app.
//
// The v3 EmitterV3 struct (emit.go) uses the same name space with a
// distinct name and is deleted in P1.11.
type Emitter interface {
	// App returns the short name (e.g. "ghostty"). Matches the baseline
	// filename and hints/overrides lookup key.
	App() string

	// Filename is the output filename inside <theme>/derived/.
	Filename() string

	// Emit writes the full 4-block output for theme t to w. Emitters
	// typically call EmitStandard which handles baseline/hints/overrides
	// and delegates the semantic block to a callback.
	Emit(t *Theme, w io.Writer) error
}

// SemanticFn writes the emitter-specific color block. Called by
// EmitStandard between the baseline and hints blocks.
type SemanticFn func(t *Theme, w io.Writer) error

// HintsFn writes the emitter-specific hints block: reads known keys from
// t.Hint(app) and emits any settings it recognizes. Unknown keys are
// ignored. If an emitter does not read hints, pass NoHints.
type HintsFn func(t *Theme, w io.Writer) error

// NoHints is the null HintsFn.
func NoHints(_ *Theme, _ io.Writer) error { return nil }

// EmitStandard writes the standard 4-block pipeline in order:
//
//  1. Header    — `<commentPrefix> generated by themes v4 from <theme>/theme.json — DO NOT EDIT`
//  2. Baseline  — content from internal/palette/baselines/<app>.tmpl
//  3. Semantic  — output of semantic(t, w)
//  4. Hints     — output of hints(t, w)
//  5. Overrides — verbatim overrides.<app> then contents of overrides.<app>_path
//
// commentPrefix is the app's comment syntax ("#" for shell/config,
// "--" for lua, "//" for jsonc, ""...). If empty, block markers are
// omitted so the output stays valid for formats that don't tolerate
// comments (opencode bare filename, strict JSON, XML property lists —
// those emitters typically don't call EmitStandard and do their own
// sequencing).
//
// If baseline lookup returns an empty string (missing .tmpl), the
// baseline block is skipped silently. This matches P1.2's contract:
// adding an emitter before its baseline is authored is a warning, not
// a failure.
func EmitStandard(t *Theme, w io.Writer, app string, commentPrefix string, semantic SemanticFn, hints HintsFn) error {
	if t == nil {
		return fmt.Errorf("EmitStandard(%s): nil theme", app)
	}
	if semantic == nil {
		return fmt.Errorf("EmitStandard(%s): nil SemanticFn", app)
	}
	if hints == nil {
		hints = NoHints
	}

	// 1. Header
	if commentPrefix != "" {
		if _, err := fmt.Fprintf(w, "%s generated by themes v4 from %s/theme.json — DO NOT EDIT\n", commentPrefix, t.Name); err != nil {
			return err
		}
	}

	// 2. Baseline
	base, err := Baseline(app, t)
	if err != nil {
		return fmt.Errorf("EmitStandard(%s): baseline: %w", app, err)
	}
	if base != "" {
		if commentPrefix != "" {
			if _, err := fmt.Fprintf(w, "\n%s --- baseline ---\n", commentPrefix); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, base); err != nil {
			return err
		}
		if !endsWithNewline(base) {
			if _, err := io.WriteString(w, "\n"); err != nil {
				return err
			}
		}
	}

	// 3. Semantic
	if commentPrefix != "" {
		if _, err := fmt.Fprintf(w, "\n%s --- semantic ---\n", commentPrefix); err != nil {
			return err
		}
	}
	if err := semantic(t, w); err != nil {
		return fmt.Errorf("EmitStandard(%s): semantic: %w", app, err)
	}

	// 4. Hints
	if commentPrefix != "" {
		if _, err := fmt.Fprintf(w, "\n%s --- hints ---\n", commentPrefix); err != nil {
			return err
		}
	}
	if err := hints(t, w); err != nil {
		return fmt.Errorf("EmitStandard(%s): hints: %w", app, err)
	}

	// 5. Overrides
	inline := t.OverrideInline(app)
	sidecar := t.OverridePath(app)
	if inline != "" || sidecar != "" {
		if commentPrefix != "" {
			if _, err := fmt.Fprintf(w, "\n%s --- overrides ---\n", commentPrefix); err != nil {
				return err
			}
		}
		if inline != "" {
			if _, err := io.WriteString(w, inline); err != nil {
				return err
			}
			if !endsWithNewline(inline) {
				if _, err := io.WriteString(w, "\n"); err != nil {
					return err
				}
			}
		}
		if sidecar != "" {
			data, err := os.ReadFile(sidecar)
			if err != nil {
				return fmt.Errorf("EmitStandard(%s): read override sidecar %s: %w", app, sidecar, err)
			}
			if _, err := w.Write(data); err != nil {
				return err
			}
		}
	}
	return nil
}

func endsWithNewline(s string) bool {
	return len(s) > 0 && s[len(s)-1] == '\n'
}

// EmittersV4 is the ordered registry of v4 emitters, populated by the
// wave 1-5 tasks (P1.4 through P1.8). Kept empty here so the package
// compiles between waves.
var EmittersV4 []Emitter
