package palette

import (
	"bufio"
	"bytes"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

// v4 nvim emitter — writes a LazyVim-compatible plugin spec table.
//
// The user's configs-shared/.config/nvim/lua/plugins/colorscheme.lua
// reads ~/.config/themes/.current/neovim.lua and pipes the returned
// table to LazyVim's plugin loader. So this emitter MUST:
//
//  1. Write a file named `neovim.lua` (not `nvim.lua`).
//  2. Emit `return { ... }` — a Lua table, not an imperative script.
//  3. Put the colorscheme plugin's setup+load in a `config = function()`
//     block so LazyVim runs it at plugin load time.
//
// Hints consumed:
//   hints.nvim.plugin      — plugin repo, e.g. "ribru17/bamboo.nvim"
//   hints.nvim.colorscheme — colorscheme name for pcall fallback path
//   hints.nvim.fallback    — secondary colorscheme name to try
//
// Overrides consumed:
//   overrides.nvim         — raw Lua string, injected as config body
//   overrides.nvim_path    — sidecar file, read and injected as config body
//   overrides/nvim.lua     — implicit sidecar path relative to theme dir

type nvimEmitter struct{}

func (nvimEmitter) App() string      { return "nvim" }
func (nvimEmitter) Filename() string { return "neovim.lua" }

func (e nvimEmitter) Emit(t *Theme, w io.Writer) error {
	// Header comment mirrors EmitStandard's shape but this file must be
	// pure Lua (no `# --- semantic ---` markers) because dofile parses it.
	fmt.Fprintf(w, "-- generated by themes v4 from %s/theme.json — DO NOT EDIT\n", t.Name)

	plugin, colorscheme, fallback := "", "default", ""
	if h := t.Hint("nvim"); h != nil {
		if v, ok := h["plugin"].(string); ok && v != "" {
			plugin = v
		}
		if v, ok := h["colorscheme"].(string); ok && v != "" {
			colorscheme = v
		}
		if v, ok := h["fallback"].(string); ok && v != "" {
			fallback = v
		}
	}

	configBody := nvimConfigBody(t, colorscheme, fallback)

	if plugin == "" {
		// Fallback shape: no dedicated colorscheme plugin. Emit a
		// LazyVim opts spec so LazyVim's own colorscheme mechanism
		// picks up the name. This works for LazyVim built-in themes
		// (catppuccin, tokyonight, rose-pine, everforest, gruvbox).
		fmt.Fprintf(w, "\nreturn {\n")
		fmt.Fprintf(w, "\t\"LazyVim/LazyVim\",\n")
		fmt.Fprintf(w, "\topts = {\n")
		fmt.Fprintf(w, "\t\tcolorscheme = %q,\n", colorscheme)
		fmt.Fprintf(w, "\t},\n")
		fmt.Fprintf(w, "}\n")
		return nil
	}

	fmt.Fprintf(w, "\nreturn {\n")
	fmt.Fprintf(w, "\t%q,\n", plugin)
	fmt.Fprintf(w, "\tname = %q,\n", colorscheme)
	fmt.Fprintf(w, "\tlazy = false,\n")
	fmt.Fprintf(w, "\tpriority = 1000,\n")
	fmt.Fprintf(w, "\tconfig = function()\n")
	indentedBody(w, configBody, "\t\t")
	fmt.Fprintf(w, "\tend,\n")
	fmt.Fprintf(w, "}\n")
	return nil
}

// nvimConfigBody returns the Lua source that goes inside the plugin's
// config = function() block. Precedence:
//
//  1. overrides.nvim string, verbatim.
//  2. overrides.nvim_path or the implicit <themeDir>/overrides/nvim.lua
//     sidecar file, verbatim.
//  3. Fallback: pcall the primary colorscheme, then the fallback.
func nvimConfigBody(t *Theme, colorscheme, fallback string) string {
	if t.Overrides != nil {
		if raw, ok := t.Overrides["nvim"]; ok && strings.TrimSpace(raw) != "" {
			return raw
		}
		if path, ok := t.Overrides["nvim_path"]; ok && path != "" {
			if !filepath.IsAbs(path) {
				path = filepath.Join(t.Dir, path)
			}
			if b, err := os.ReadFile(path); err == nil {
				return string(b)
			}
		}
	}
	// Implicit sidecar at <themeDir>/overrides/nvim.lua.
	implicit := filepath.Join(t.Dir, "overrides", "nvim.lua")
	if b, err := os.ReadFile(implicit); err == nil {
		return string(b)
	}
	// No sidecar: default setup+load fallback.
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "local ok, mod = pcall(require, %q)\n", colorscheme)
	fmt.Fprintf(&buf, "if ok then\n")
	fmt.Fprintf(&buf, "\tif type(mod.setup) == \"function\" then mod.setup({}) end\n")
	fmt.Fprintf(&buf, "\tif type(mod.load) == \"function\" then mod.load() end\n")
	fmt.Fprintf(&buf, "end\n")
	fmt.Fprintf(&buf, "local ok2 = pcall(vim.cmd.colorscheme, %q)\n", colorscheme)
	if fallback != "" {
		fmt.Fprintf(&buf, "if not ok2 then pcall(vim.cmd.colorscheme, %q) end\n", fallback)
	}
	return buf.String()
}

// indentedBody writes body to w with each non-empty line prefixed by
// indent. Preserves blank lines verbatim so the reader sees a clean
// grouping.
func indentedBody(w io.Writer, body, indent string) {
	scanner := bufio.NewScanner(strings.NewReader(body))
	scanner.Buffer(make([]byte, 64*1024), 4*1024*1024)
	for scanner.Scan() {
		line := scanner.Text()
		if strings.TrimSpace(line) == "" {
			fmt.Fprintln(w)
			continue
		}
		fmt.Fprintf(w, "%s%s\n", indent, line)
	}
}
