# generated by themes v4 from osaka-jade/theme.json — DO NOT EDIT

# --- baseline ---
# fzf baseline — theme-independent options.
# The semantic block below appends `export FZF_DEFAULT_OPTS_HIGH_CONTRAST`
# with concrete color pairs.

# Layout / behavior defaults (theme-independent).
export FZF_DEFAULT_OPTS_LAYOUT="--layout=reverse --border --height=90%"
export FZF_DEFAULT_OPTS_PREVIEW="--preview-window=right:60%:wrap"

# --- semantic ---
export FZF_DEFAULT_OPTS_COLORS="--color=fg:#C1C497,bg:-1,hl:#549E6A,fg+:#C1C497,bg+:#23372B,hl+:#E5C736,info:#627A6C,prompt:#549E6A,pointer:#E5C736,marker:#E5C736,spinner:#549E6A,header:#7AA2F7,border:#509475"

# --- hints ---
