# generated by themes v4 from osaka-jade/theme.json — DO NOT EDIT

# --- baseline ---
#!/usr/bin/env bash
# sketchybar baseline — theme-independent bar geometry.
# The semantic block below exports color vars (BAR_BG, FG, ACCENT, ...)
# consumed by the sketchybarrc plugin scripts.

# Bar geometry defaults; overridable via hints.sketchybar.{barHeight,cornerRadius}.
export BAR_HEIGHT=25
export BAR_CORNER_RADIUS=0
export BAR_MARGIN=0
export BAR_Y_OFFSET=0

# Font defaults; overridable via typography hints.
export BAR_FONT="MonaspiceNe Nerd Font"
export BAR_ICON_FONT="MonaspiceNe Nerd Font"

# --- semantic ---
export BAR_BG=0xd0111c18
export BAR_BORDER=0xff509475
export FG=0xffc1c497
export FG_MUTED=0xff627a6c
export FG_BRIGHT=0xff9eebb3
export ACCENT=0xff549e6a
export ACCENT_BRIGHT=0xff63b07a
export ACCENT_ON=0xff000000
export HIGHLIGHT=0xff549e6a
export RED=0xffff5345
export YELLOW=0xffe5c736
export GREEN=0xff63b07a
export CYAN=0xff2dd5b7
export MAGENTA=0xffd2689c
export INFO=0xff7aa2f7
export TEAL=0xff509475
export JADE=0xff549e6a
export VOLUME=0xff2dd5b7
export PERCENTAGE=0xffc1c497
export SURFACE=0xff0d1512
export SURFACE_LIGHT=0x44509475
export ICON=0xffc1c497
export CHARGING=0xffe5c736
export FOCUSED=0xffe5c736
export FOCUSED_WORKSPACE=0xff549e6a
export FOCUSED_WORKSPACE_COLOR=0xff549e6a
export NON_EMPTY=0xffc1c497
export BADGE=0xffe5c736

# --- hints ---
export BAR_HEIGHT=28
export BAR_CORNER_RADIUS=6
