# generated by themes v4 from osaka-jade/theme.json — DO NOT EDIT

# --- baseline ---
# zsh-syntax-highlighting baseline — theme-independent flags.
# The semantic block below sets ZSH_HIGHLIGHT_STYLES[<scope>] entries.

# Which highlighter families are active (theme-independent).
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)

# Ensure the array exists so the semantic block's assignments succeed
# even before syntax-highlighting has been sourced.
typeset -gA ZSH_HIGHLIGHT_STYLES

# --- semantic ---
ZSH_HIGHLIGHT_STYLES[comment]=fg=#627A6C
ZSH_HIGHLIGHT_STYLES[default]=fg=#C1C497
ZSH_HIGHLIGHT_STYLES[unknown-token]=fg=#FF5345
ZSH_HIGHLIGHT_STYLES[reserved-word]=fg=#BB9AF7
ZSH_HIGHLIGHT_STYLES[alias]=fg=#E5C736
ZSH_HIGHLIGHT_STYLES[builtin]=fg=#E5C736
ZSH_HIGHLIGHT_STYLES[function]=fg=#E5C736
ZSH_HIGHLIGHT_STYLES[command]=fg=#E5C736
ZSH_HIGHLIGHT_STYLES[path]=fg=#7AA2F7
ZSH_HIGHLIGHT_STYLES[globbing]=fg=#E5C736
ZSH_HIGHLIGHT_STYLES[history-expansion]=fg=#E5C736
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]=fg=#63B07A
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]=fg=#63B07A
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]=fg=#63B07A
ZSH_HIGHLIGHT_STYLES[assign]=fg=#E5C736
ZSH_HIGHLIGHT_STYLES[named-fd]=fg=#7AA2F7
ZSH_HIGHLIGHT_STYLES[numeric-fd]=fg=#2DD5B7
ZSH_HIGHLIGHT_STYLES[bracket-error]=fg=#FF5345
ZSH_HIGHLIGHT_STYLES[bracket-level-1]=fg=#549E6A
ZSH_HIGHLIGHT_STYLES[bracket-level-2]=fg=#E5C736
ZSH_HIGHLIGHT_STYLES[bracket-level-3]=fg=#7AA2F7
ZSH_HIGHLIGHT_STYLES[bracket-level-4]=fg=#E5C736
ZSH_HIGHLIGHT_STYLES[cursor-matchingbracket]=fg=#63B07A

# --- hints ---
